### PR TITLE
feat: Artifactory Query Language integration

### PR DESCRIPTION
**Pull request by anancarv**
## Description

This PR aims to implement [Artifactory Query Language (AQL)](https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Language) in order to let you uncover any data related to the artifacts and builds stored within Artifactory. It also removes all deprecated functions.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Unit tests associated to this feature can be found in the file `tests/test_aql.py`. We use [responses](https://github.com/getsentry/responses) to mock HTTP requests in order not to attack directly a specific Artifactory instance. Two things are tested:

- [x] Test success: Good query parameters, find the repository named `libs-release-local`
- [x] Test failed: Bad query parameters

## Checklist:

- [x] My PR is ready for prime time! 
- [x] All commits have a correct title
- [x] Readme has been updated
- [x] Quality tests are green (see Codacy)
- [x] Automated tests are green (see pipeline)

### CODE REVIEW

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test_aql.py  2
- pyartifactory/models/Aql.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Artifactory Query language doc: https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Language

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- pyartifactory/objects.py  -1
         

Complexity increasing per file
==============================
- tests/test_aql.py  2
- pyartifactory/models/Aql.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyartifactory/models/Aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ pyartifactory/objects.py  1
         

Complexity increasing per file
==============================
- pyartifactory/models/Aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- pyartifactory/objects.py  -6
         

Complexity increasing per file
==============================
- tests/test_aql.py  2
- pyartifactory/models/aql.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyartifactory/models/aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyartifactory/models/aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyartifactory/models/aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by anancarv** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyartifactory/models/aql.py  1
- tests/test_aql.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Ananias/python-artifactory/pullRequest?prid=4779609&bid=15923038)

**Comment by saper** [comment]
I have rebased this to #72 - skipped some extra changes from this PR, like adding "from" to exceptions.

**Pull request closed without merging**
